### ISSUE TITLE
Doesn't work with Japanese version

### ISSUE THREAD

**Issue by NANELLON** [vswarte/eldenring_force_dynamic_shadows#2]
The Japanese version of the game has a different version of the exe so the offset is different. Mods often match a pattern of bytes in memory to find the target address which avoids this issue. Rust has a built-in aobscan that might work for this. Pattern matching would mostly keep the mod functioning when game updates are released too so definitely consider it for future versions

**Comment by vswarte** [comment]
@NANELLON can you send me the exe somehow? Feel free to add me on discord: chainfailure

**Comment by vswarte** [comment]
This has been implemented per v1.1.0
