### ISSUE TITLE
Broken on 1.12

### ISSUE THREAD

**Issue by jlrouzies-fr** [vswarte/eldenring_force_dynamic_shadows#5]
Hello!

Doesn't seem to work on 1.12, could you update it please?

Thanks!

**Comment by vswarte** [comment]
Hi try this build https://github.com/vswarte/eldenring_force_dynamic_shadows/actions/runs/9650162397

**Comment by jlrouzies-fr** [comment]
It works, thanks!

Although the game had a small update 1.12.2 today if I do not mistake, not sure if it impacted it

**Comment by vswarte** [comment]
That update seemingly didn't change the exe so 🤷
